version: "3.1"
services:
    ebanx-webserver:
      image: nginx:alpine
      container_name: ebanx-webserver
      working_dir: /src
      volumes:
          - .:/src
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    ebanx-php-fpm:
      build: .docker/php-fpm
      container_name: ebanx-php-fpm
      working_dir: /src
      volumes:
        - .:/src
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

